### ISSUE TITLE
[suggestion] Some graph improvements

### ISSUE THREAD

**Issue by Fnige** [eloh-mrow/death-tracker#14]
Nice graph, could do with some extra things.

Firstly our mind wants to process the graph differently so having some "likelihood to pass" graph would be nice. (idk how to word it but make it go down instead of the spiky shenanigans) 

Secondly being able to zoom in or have it zoomed in to a slight bit after your new best would be nice too

Its midnight so god knows if I worded this well at all so have fun! :)

**Comment by Fnige** [comment]
oh i forgot to comment to this, but for the first one i meant for it to be more of a "likelihood to pass x percent" and for the latter i meant that instead of showing 0-100% on the graph, you can instead make it show 0-61% for example

the wording is confusing, sorry about that but thats what you get for writing at midnight

**Comment by Fnige** [comment]
![image](https://github.com/eloh-mrow/death-tracker/assets/35159947/6be7975d-a27c-4b38-a20e-102c7be9e319)
Ok so something like this, hopefully this would show it better

**Comment by Craanky** [comment]
i agree this would be awesome, like ydis did it

**Comment by abb2k** [comment]
> ![image](https://private-user-images.githubusercontent.com/35159947/334313906-6be7975d-a27c-4b38-a20e-102c7be9e319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODM1NjcsIm5iZiI6MTcxOTg4MzI2NywicGF0aCI6Ii8zNTE1OTk0Ny8zMzQzMTM5MDYtNmJlNzk3NWQtYTI3Yy00YjM4LWEyMGUtMTAyYzdiZTllMzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxMjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NTA4MGVjMjNhOWZkYzY2MDc0ODdkMzYyNGE5MmI4MjAwM2M5MWM3ZTA2NGE3M2MxNTIwZDU2NjFjMDUyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtKZVeQz2T96E1nkA6mLQysK5Ss4Yp7kF4bn07BH0U4) Ok so something like this, hopefully this would show it better

ok i think i understand what u are saying but i dont think i need to implement this (even tho it would be cool) and i wont rn cz i dont wanna overcomplicate things people are already having a hard time understanding the graphs, but anyways the current graph does kinda show you this info but in a different way :) my current graph is if u basically combined the two graphs you showed an example of here into one

it doesnt show u the amount of times gotten to a % like this 'room entries' graph shows but it does use that info to calculate the passrate for stuff which is basically like the 'check rates' but it just has a 100% passrate for every point you never died to (cz u never died there so ur passrate is 100% lol) and that makes my graph look more spiky kinda

i designed my graph to be just like the ydis graph, it would be cool to add more but i dont wanna overcomplicate things in the mod and dont have as much time to make that feature rn but i really appreciate ur suggestion :D

**Comment by abb2k** [comment]
heya if you have any graph ideas im open for suggestions now :D
