### ISSUE TITLE
Suggestion: Point Sizes

### ISSUE THREAD

**Issue by nbieberitz** [eloh-mrow/death-tracker#16]
On mobile, it's difficult to select the points on the graph.  Could there be something like a slider to alter the point size?

**Comment by abb2k** [comment]
sure :) maybe in a future update

**Comment by nbieberitz** [comment]
Ok, thank you for considering my suggestion!

**Comment by abb2k** [comment]
i am temporarily adding this option into the mods settings :D i will later add this into the actual graph layer when i anyways rework it :) (ill release the update later today)

**Comment by nbieberitz** [comment]
Thank you for considering my suggestion.
