### ISSUE TITLE
Game crashes if you hit a checkpoint object while in normal mode (not platformer)

### ISSUE THREAD

**Issue by Aarxy** [eloh-mrow/death-tracker#17]
Android 64
Such a random crash

**Comment by abb2k** [comment]
this issue doesnt happen to me can u send a crashlog or something

**Comment by Aarxy** [comment]
[Crash 2024-07-04 16.31.40.dmp](https://github.com/user-attachments/files/16100188/Crash.2024-07-04.16.31.40.dmp)

**Comment by abb2k** [comment]
r u sure this is a death tracker issue and not some other mod or bug? i dont really know how to read android crash logs well but i dont see any mentions of death tracker in this log so idk

**Comment by Aarxy** [comment]
Idk but it happens only when its enabled even with all other mods disabled (except node ids which alone doesnt crash either)
