### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by thriftybrake446** [eloh-mrow/death-tracker#18]
"This" isn't capitalized, and percents is spelled wrong.
![Screenshot 2024-08-09 142908](https://github.com/user-attachments/assets/e0105777-eee2-448a-983a-10d6e42f1139)

**Comment by thriftybrake446** [comment]
also i might have looked through the code and i think i found where it is. lmao
https://github.com/eloh-mrow/death-tracker/blob/a8210a656d64aec8f68e915951ed3df572fb82e2/src/layers/DTLayer.cpp#L1418

**Comment by abb2k** [comment]
Woops lol
Ye i had lots of typos while making this mod and thats mainly cz english isn't my first language lol
Ty for reporting this ill fix it
