### ISSUE TITLE
Suggestion: be able to update deaths if you dont use the mod

### ISSUE THREAD

**Issue by Ev212** [eloh-mrow/death-tracker#19]
you should be able to update your deaths when you turn off the mod and turn it back on

**Comment by Hanifinio** [comment]
But how will it know

**Comment by Ev212** [comment]
Is there a place where gd stores your deaths

**Comment by Hanifinio** [comment]
No because it would just be information that you can't even access. Your default pfp says it all

**Comment by Ev212** [comment]
Oh ok
