### ISSUE TITLE
Game crashes A LOT, here is the crash log

### ISSUE THREAD

**Issue by FitPinguino** [eloh-mrow/death-tracker#2]
2024-02-09T13:08:14+0100
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "elohmrow.death_tracker" mod. Please submit this crash report to its developers (ElohmroW) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.16
Loader Commit: 4f21162
Bindings Commit: c901cbb
Installed mods: 30
Problems: 1

== Exception Information ==
Faulty Module: D:\MA\GD TEST\GEOMETRY DASH GEODE\geode\unzipped\elohmrow.death_tracker\elohmrow.death_tracker.dll
Faulty Mod: elohmrow.death_tracker
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 5BECC1CB (elohmrow.death_tracker.dll + 2c1cb)
Number Parameters: 2

== Stack Trace ==
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\geode\unzipped\elohmrow.death_tracker\elohmrow.death_tracker.dll + 2c1cb
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\geode\unzipped\elohmrow.death_tracker\elohmrow.death_tracker.dll + 195fe
 - 0D032357
 - 0DCD259E
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\geode\unzipped\cvolton.betterinfo\cvolton.betterinfo.dll + 1f811
 - 0DCD23C3
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\GeometryDash.exe + 1bc05a
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\libcocos2d.dll + 106e36 (cocos2d::CCScheduler::update + 134)
 - 02BD1CF6
 - 02BD1B17
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\geode\unzipped\gdutilsdevs.gdutils\gdutilsdevs.gdutils.dll + 1e4e6
 - 02BD1B17
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\geode\unzipped\gdutilsdevs.gdutils\gdutilsdevs.gdutils.dll + 1e506
 - 02BD1B17
 - 02BD1B17
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\GeometryDash.exe + 3c12d8
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\Geode.dll + c65a6 (geode::utils::web::AsyncWebRequest::userAgent + 12406)
 - D:\MA\GD TEST\GEOMETRY DASH GEODE\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 28557240
EBX: 1d34e010
ECX: 6b044e28
EDX: 00000002
EBP: 001df224
ESP: 001df214
EDI: 1d34e010
ESI: 29a139d0
EIP: 5becc1cb

== Installed Mods ==
x | [v1.0.4] abb2k.backup
x | [v1.0.1] alphalaneous.happy_textures
x | [v1.0.0] alphalaneous.playercolorselect
x | [v1.0.1] arkane.dl-team-icons
x | [v1.0.5] b1rtek.gddlintegration
x | [v1.0.5] bitz.customprofiles
x | [v1.1.2] capeling.demons_in_garage_2.2
x | [v4.0.0-alpha.13] cvolton.betterinfo
! | [v1.0.4] dankmeme.globed2
x | [v1.0.1] doom.doomsutils
x | [v1.0.1] ekv.hidePauseMenuHack
x | [v1.2.0] elnexreal.copy_song_id
x | [v1.4.3] elohmrow.death_tracker
x | [v1.2.14] gdutilsdevs.gdutils
  | [v1.4.0] geode.custom-keybinds
x | [v2.0.0-beta.16] geode.loader
x | [v1.3.0] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v1.0.2] mat.run-info
x | [v1.1.0] mat.scroll-zoom
x | [v1.2.1] oatmealine.ids_integration
x | [v1.2.0] oatmealine.nlw_integration
x | [v1.6.1] prevter.openhack
x | [v1.1.0] thesillydoggo.better_startpos_menu
x | [v1.0.0] thesillydoggo.entersearch
x | [v1.6.2] undefined0.gdtweaks
x | [v1.1.1] uproxide.geodedevelopers
x | [v1.0.2] weebify.coins_in_pause_menu
x | [v1.0.0] xanii.youtubers

**Comment by FitPinguino** [comment]
It crashes when browsing levels, and deleting them with the "X" on the top right, sometimes it crashes

**Comment by eloh-mrow** [comment]
@FitPinguino can you check to see if this is happening without any other mods enabled?

**Comment by FitPinguino** [comment]
> @FitPinguino can you check to see if this is happening without any other mods enabled?

I disabled the mod and it doesnt crash anymore

**Comment by eloh-mrow** [comment]
Closed as you haven't provided any further information for reproduction
