### ISSUE TITLE
(suggestion) start counting resetting as deaths

### ISSUE THREAD

**Issue by 7hat3eird0ne** [eloh-mrow/death-tracker#22]
it is rlly annoying that i usualy reset instead of playing out the endscreen when i do a run to hundred meaning that my nice to hundred runs dont appear

would be really nice if it counted them too

**Comment by abb2k** [comment]
how exactly am i going to implement this tho? the user would need to specify on which run do runs that get reset at another specified %+ will be counted as another % specified by the user and this would take a new window of ui and i know most people arent gonna try to understand how it works

**Comment by 7hat3eird0ne** [comment]
Huh, cant u just add a setting in the mod which if checked on makes it that the percentage at which the player is at time of reset gets put into the death tracker assuming other conditions? I dont understand whats the need to make it so that if u reset somewhere it will work, if someone considers reset as death at some point they arent gonna consider it as not at other point

oh it is closed cuz it was not understood amazing

**Comment by abb2k** [comment]
yeah i wanna add a feature where you can toggle resetting counting as deaths on levels i think that will help
