### ISSUE TITLE
Super Slow Performance

### ISSUE THREAD

**Issue by AksLolCoding** [eloh-mrow/death-tracker#23]
Opening the death tracker menu freezes the game for like 10 seconds even on a lvl with only like 500 attempts. If i try to press something while the game is frozen then it just crashes. And this is on the regular menu (with the percentage counts), not the graph. It's not my device since I can run 100k obj levels without lag.

**Comment by abb2k** [comment]
that doesnt sound great :( i always ran everything just fine so idk why this is happening

i also dont have much of an idea for how to reduce this lag but i do think i can make it calculate in the background so it doesnt get your game stuck, and your stats on the level will load after it finishes calculating :D

**Comment by abb2k** [comment]
im closing this issue because i have made a change in the mod (next update) that should improve this :) feel free to reopen this issue if (after updating) this still occurs
