### ISSUE TITLE
Mis-spelling?

### ISSUE THREAD

**Issue by nbieberitz** [eloh-mrow/death-tracker#25]
Idk, but this could be a misspelled word, "accrued," and wanted to confirm if that was the right word choice. 
![Screenshot_20241117_235819_Geode](https://github.com/user-attachments/assets/037a51b8-33df-44ce-9b77-c069d3ad050c)

**Comment by abb2k** [comment]
lol 💀 why does this keep happening to me lol i wanted to type accurate :(( ty for reporting this tho :D

**Comment by nbieberitz** [comment]
Of course!
