### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by nbieberitz** [eloh-mrow/death-tracker#26]
What's with the date on this session?
![Screenshot_20241118_000827_Geode](https://github.com/user-attachments/assets/cde11bac-063b-4d98-9c82-cca6bd71a4d8)

**Comment by abb2k** [comment]
i dont completely know why this happens, this has been a thing for a while now and i dont know if i can fix it :( sorry
i can try to find out why this happens but i cant promise to find a good solution

at least from what ive seen this doesnt happen on every session

**Comment by nbieberitz** [comment]
Thanks for trying. I want to also thank you for all the hours of coding you've spent making it as functional as possible. This is one of the best mods out there.

**Comment by abb2k** [comment]
ty :D i appreciate it
