### ISSUE TITLE
"All Sessions" Suggestion 

### ISSUE THREAD

**Issue by nbieberitz** [eloh-mrow/death-tracker#28]
(If there's not this already) There should be an option to show all sessions. In the file attached to this, I drew an arrow to the arrow going to left. My suggestion is that if you're already selected on session 1 out of whatever, and you hit the left arrow, because there's not a session 0, that could show all sessions combined, and the text that shows the "1/4" for example, below the "Sessions" label could turn to say "All." To add on to my idea, if it's set to show "All" sessions, the left arrow could fade, be invisible, or at least be smaller, so that it makes more sense for users. The right arrow would just return to show just session 1 again.

 If this is available somewhere in the mod and I didn't find it, let me know. If so, please forgive me for wasting your time reading this.

![Screenshot_20241118_222433_Geode](https://github.com/user-attachments/assets/3bfa269b-5152-43c7-8a15-5a2a2d0c9977)

**Comment by abb2k** [comment]
the sessions are just your normal attempt but the ones you did on that session :D that means that if you wanna see all the progress on all sessions you just need to look at the normal from 0 and runs :) these have all your attempts displayed

so i dont think this feature is needed but ty for the suggestion anyways!

**Comment by nbieberitz** [comment]
Ok, that's fine
