### ISSUE TITLE
when opening a mod or going to the settings mod it crashes when going back

### ISSUE THREAD

**Issue by Helloausername** [eloh-mrow/death-tracker#7]
android 32bit

[Crash 2024-03-28 07.13.13.dmp](https://github.com/eloh-mrow/death-tracker/files/14784277/Crash.2024-03-28.07.13.13.dmp)
[Crash 2024-03-28 07.13.50.dmp](https://github.com/eloh-mrow/death-tracker/files/14784278/Crash.2024-03-28.07.13.50.dmp)
[Crash 2024-03-28 07.12.57.dmp](https://github.com/eloh-mrow/death-tracker/files/14784279/Crash.2024-03-28.07.12.57.dmp)
[Crash 2024-03-28 07.13.30.dmp](https://github.com/eloh-mrow/death-tracker/files/14784280/Crash.2024-03-28.07.13.30.dmp)

**Comment by DadamaldaDad** [comment]
Happens for me too (Android64, Geode beta26)
But only when I exit using the Android back button, it's fine when I use the back arrow.
